name: test
channels:
  - defaults
dependencies:
  - aiofiles=22.1.0=py38haa95532_0
  - aiosqlite=0.18.0=py38haa95532_0
  - anyio=3.5.0=py38haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h2bbff1b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=23.1.0=py38haa95532_0
  - babel=2.11.0=py38haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py38haa95532_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.5=py38h080aedc_0
  - brotli=1.0.9=h2bbff1b_7
  - brotli-bin=1.0.9=h2bbff1b_7
  - brotli-python=1.0.9=py38hd77b12b_7
  - ca-certificates=2023.08.22=haa95532_0
  - certifi=2023.7.22=py38haa95532_0
  - cffi=1.15.1=py38h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=py38haa95532_0
  - comm=0.1.2=py38haa95532_0
  - contourpy=1.0.5=py38h59b6b97_0
  - cryptography=41.0.3=py38h89fc84f_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.6.7=py38hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py38haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - giflib=5.2.1=h8cc25b3_3
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.4=py38haa95532_0
  - importlib-metadata=6.0.0=py38haa95532_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - importlib_resources=6.1.0=py38haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46319
  - ipykernel=6.25.0=py38h9909e9c_0
  - ipython=8.12.2=py38haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=8.0.4=py38haa95532_0
  - jedi=0.18.1=py38haa95532_1
  - jinja2=3.1.2=py38haa95532_0
  - jpeg=9e=h2bbff1b_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py38haa95532_0
  - jsonschema-specifications=2023.7.1=py38haa95532_0
  - jupyter=1.0.0=py38haa95532_8
  - jupyter_client=7.4.9=py38haa95532_0
  - jupyter_console=6.6.3=py38haa95532_0
  - jupyter_core=5.5.0=py38haa95532_0
  - jupyter_events=0.6.3=py38haa95532_0
  - jupyter_server=1.23.4=py38haa95532_0
  - jupyter_server_fileid=0.9.0=py38haa95532_0
  - jupyter_server_ydoc=0.8.0=py38haa95532_1
  - jupyter_ydoc=0.2.4=py38haa95532_0
  - jupyterlab=3.6.3=py38haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.22.0=py38haa95532_0
  - jupyterlab_widgets=3.0.5=py38haa95532_0
  - kiwisolver=1.4.4=py38hd77b12b_0
  - krb5=1.20.1=h5b6d351_0
  - lerc=3.0=hd77b12b_0
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_0
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.15=h906ac69_1
  - libsodium=1.0.18=h62dcd97_0
  - libtiff=4.5.1=hd77b12b_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_0
  - markupsafe=2.1.1=py38h2bbff1b_0
  - matplotlib=3.7.2=py38haa95532_0
  - matplotlib-base=3.7.2=py38h4ed8f06_0
  - matplotlib-inline=0.1.6=py38haa95532_0
  - mistune=2.0.4=py38haa95532_0
  - mkl=2023.1.0=h6b88ed4_46357
  - mkl-service=2.4.0=py38h2bbff1b_1
  - mkl_fft=1.3.8=py38h2bbff1b_0
  - mkl_random=1.2.4=py38h59b6b97_0
  - munkres=1.1.4=py_0
  - nbclassic=0.5.5=py38haa95532_0
  - nbclient=0.8.0=py38haa95532_0
  - nbconvert=7.10.0=py38haa95532_0
  - nbformat=5.9.2=py38haa95532_0
  - nest-asyncio=1.5.6=py38haa95532_0
  - notebook=6.5.4=py38haa95532_1
  - notebook-shim=0.2.2=py38haa95532_0
  - numexpr=2.8.4=py38h7b80656_1
  - numpy=1.24.3=py38h79a8e48_1
  - numpy-base=1.24.3=py38h8a87ada_1
  - openjpeg=2.4.0=h4fc8c34_0
  - openssl=3.0.12=h2bbff1b_0
  - packaging=23.1=py38haa95532_0
  - pandas=2.0.3=py38h4ed8f06_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.0.1=py38h045eedc_0
  - pip=23.3=py38haa95532_0
  - pkgutil-resolve-name=1.3.10=py38haa95532_0
  - platformdirs=3.10.0=py38haa95532_0
  - ply=3.11=py38_0
  - pooch=1.7.0=py38haa95532_0
  - prometheus_client=0.14.1=py38haa95532_0
  - prompt-toolkit=3.0.36=py38haa95532_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - psutil=5.9.0=py38h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py38haa95532_1
  - pyopenssl=23.2.0=py38haa95532_0
  - pyparsing=3.0.9=py38haa95532_0
  - pyqt=5.15.10=py38hd77b12b_0
  - pyqt5-sip=12.13.0=py38h2bbff1b_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.18=h1aa4202_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py38haa95532_0
  - python-json-logger=2.0.7=py38haa95532_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2023.3.post1=py38haa95532_0
  - pywin32=305=py38h2bbff1b_0
  - pywinpty=2.0.10=py38h5da7b33_0
  - pyyaml=6.0.1=py38h2bbff1b_0
  - pyzmq=23.2.0=py38hd77b12b_0
  - qt-main=5.15.2=h19c9488_10
  - qtconsole=5.4.2=py38haa95532_0
  - qtpy=2.2.0=py38haa95532_0
  - referencing=0.30.2=py38haa95532_0
  - requests=2.31.0=py38haa95532_0
  - rfc3339-validator=0.1.4=py38haa95532_0
  - rfc3986-validator=0.1.1=py38haa95532_0
  - rpds-py=0.10.6=py38h062c2fa_0
  - scipy=1.10.1=py38hdcfc7df_1
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=68.0.0=py38haa95532_0
  - sip=6.7.12=py38hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py38haa95532_1
  - soupsieve=2.5=py38haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=h59b6b97_0
  - terminado=0.17.1=py38haa95532_0
  - tinycss2=1.2.1=py38haa95532_0
  - tk=8.6.12=h2bbff1b_0
  - tomli=2.0.1=py38haa95532_0
  - traitlets=5.7.1=py38haa95532_0
  - typing-extensions=4.7.1=py38haa95532_0
  - typing_extensions=4.7.1=py38haa95532_0
  - urllib3=1.26.18=py38haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - websocket-client=0.58.0=py38haa95532_4
  - wheel=0.41.2=py38haa95532_0
  - widgetsnbextension=4.0.5=py38haa95532_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - winpty=0.4.3=4
  - xz=5.4.2=h8cc25b3_0
  - y-py=0.5.9=py38hb6bf4ef_0
  - yaml=0.2.5=he774522_0
  - ypy-websocket=0.8.2=py38haa95532_0
  - zeromq=4.3.4=hd77b12b_0
  - zipp=3.11.0=py38haa95532_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
      - airsim==1.8.1
      - clarabel==0.6.0
      - cvxpy==1.4.1
      - ecos==2.0.12
      - msgpack-python==0.5.6
      - msgpack-rpc-python==0.4.1
      - opencv-contrib-python==4.8.1.78
      - osqp==0.6.3
      - pybind11==2.11.1
      - qdldl==0.1.7.post0
      - scs==3.2.3
      - simple-pid==2.0.0
      - tornado==4.5.3
prefix: C:\Users\avipa\anaconda3\envs\test
